version: '3.8'
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    networks:
      - webhook-network

  webhook-server:
    image: webhook-server:latest
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    volumes:
      - ./.env:/app/.env
    depends_on:
      - mongodb
    networks:
      - webhook-network

networks:
  webhook-network:
    driver: bridge